apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXMtdXNy
  POSTGRES_PASSWORD: cG9zdGdyZXMtcHdk
